trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    echo "Current working directory:"
    pwd
    echo "Contents of the current directory:"
    ls -al
    echo "Contents of the parent directory:"
    ls -al ..
  displayName: 'Print working directory and list files'

- script: |
    npm install -g @angular/cli@17.0.0
    npm install --legacy-peer-deps
    ng build --output-path=dist/client
  displayName: 'npm install and build'
  workingDirectory: 'client'  # Adjust this path to point to your client directory
