trigger:
  branches:
    include:
      - main
  paths:
    include:
      - DatingApp/client/**

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli@18.0.0-rc.3
    npm install --legacy-peer-deps
    ng build --configuration=production --base-href /browser/
  displayName: 'npm install and build'
  workingDirectory: '$(System.DefaultWorkingDirectory)/DatingApp/client/'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/DatingApp/client/dist/client/'
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'
